server:
  port: 10010 # 端口号
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos 地址
    gateway:
      routes:
        - id: web-service # 路由唯一标识
          uri: lb://webservice # lb 表示 LoadBalance，表示路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/web/** # 路径断言，判断路径是否以 /web 开头，如果是则符合
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: db-service
          uri: lb://dbservice
          predicates:
            - Path=/db/**
        - id: message-service
          uri: lb://messageservice
          predicates:
            - Path=/message/**
#            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
#      default-filters:
#        - AddRequestHeader=Truth, Itcast is freaking aowsome! # 1
      # Gateway 解决跨域问题
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "*" # 允许所有网站
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期